services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./stock_keeper:/code
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data/
    restart: always

  worker:
    build: .
    command: celery -A stock_keeper worker -l info -n worker
    volumes:
      - ./stock_keeper:/code
    depends_on:
      - web
      - redis
    env_file:
      - .env

  redis:
    image: "redis:alpine"